### ISSUE TITLE
ImportError: cannot import name XML_NAMESPACES

### ISSUE THREAD

**Issue by ashkov** [elifesciences/elife-crossref-xml-generation#92]
python 2.7

>>> from elifecrossref import generate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ass/.local/share/virtualenvs/crossref-bEb8iDMx/src/elifecrossref/elifecrossref/generate.py", line 10, in <module>
    from elifecrossref import body, head, utils
  File "/home/ass/.local/share/virtualenvs/crossref-bEb8iDMx/src/elifecrossref/elifecrossref/body.py", line 2, in <module>
    from elifecrossref import journal, peer_review
  File "/home/ass/.local/share/virtualenvs/crossref-bEb8iDMx/src/elifecrossref/elifecrossref/journal.py", line 3, in <module>
    from elifecrossref import dates, journal_article
  File "/home/ass/.local/share/virtualenvs/crossref-bEb8iDMx/src/elifecrossref/elifecrossref/journal_article.py", line 2, in <module>
    from elifecrossref import (
  File "/home/ass/.local/share/virtualenvs/crossref-bEb8iDMx/src/elifecrossref/elifecrossref/abstract.py", line 7, in <module>
    from elifetools.parseJATS import XML_NAMESPACES
ImportError: cannot import name XML_NAMESPACES

**Comment by gnott** [comment]
Please look to see if you have a very recent version of https://github.com/elifesciences/elife-tools library included in your virtual environment. `XML_NAMESPACES` was added there a few week ago.
